# Use an official Python runtime as a parent image
FROM python:3.11.8-bookworm

# Set the working directory in the container
WORKDIR /app

# Upgrade pip to the latest version before installing any dependencies
RUN pip install --upgrade pip

# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies from requirements.txt
RUN pip install  -r requirements.txt

# Copy the rest of the application
COPY . /app

# Set environment variables
ENV MODULE_NAME="run_api"
ENV VARIABLE_NAME="app"
ENV PORT=8000

# Inform Docker that the container listens on port 8000
EXPOSE 8000

# Run FastAPI server when the container launches
CMD ["uvicorn", "run_api:app", "--host", "0.0.0.0", "--port", "8000"]
